auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Hinleunglu
url: http://hinleung.github.io
feed: /atom.xml
author_info: <a href="http://beiyuu.com/">Hinleunglu</a>
